# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - book_network
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:10.11
    container_name: book_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
      MYSQL_USER: book_user
      MYSQL_PASSWORD:  123456
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - book_network

  nginx:
    image: nginx:latest
    container_name: book_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - book_network
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: book_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - book_network
    depends_on:
      - mariadb

  redis:
    image: redis:latest
    container_name: book_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - book_network

networks:
  book_network:
    driver: bridge

volumes:
  mariadb_data:
